#
# ~/.bashrc
#

rcdebug(){
   if [[ -n "$DEBUGRC" ]]; then
       echo "$@"
   fi
}

rcdebug "Sourcing Bashrc"
set -o vi
shopt -s cdspell
shopt -s histappend
shopt -s globstar

PS1='$ '


[[ "$TERM" = "xterm" ]] && export TERM=xterm-256color

rcsource() {
    if [[ -e "$1" ]]; then
        rcdebug "Sourcing $1"
        source "$1"
    fi
}

[[ -s "$XDG_DATA_HOME/asdf/completions/asdf.bash" ]]  && .  $XDG_DATA_HOME/asdf/completions/asdf.bash
[[ -n "$(type -P fnm)" ]] && eval "$(fnm env --use-on-cd --shell bash)"


for complfile in $XDG_DATA_HOME/bash_completions/*; do rcsource $complfile; done

for sourcefile in $XDG_CONFIG_HOME/bash/*.sh; do rcsource $sourcefile; done

unset sourcefiles
unset -f rcsource rcdebug
