#! /bin/sh
export EDITOR=nvim
export BROWSER=firefox
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

export POETRY_VIRTUALENVS_IN_PROJECT=true
export DOCKER_BUILDKIT=1

export XKB_DEFAULT_OPTIONS="caps:escape"

# Path
export PATH=$PATH:$HOME/.local/bin:$HOME/.local/bin/scripts:$HOME/.local/share/texlive/2024/bin/x86_64-linux/
[ "$(type -P ruby)" ] && export GEM_HOME=$(ruby -e 'print Gem.user_dir'); export PATH=$PATH:$GEM_HOME/bin

# App files
[[ -e $XDG_CONFIG_HOME/xdgvars/xdgvars.sh ]] && . $XDG_CONFIG_HOME/xdgvars/xdgvars.sh 

export LESSHISTFILE=$XDG_DATA_HOME/less_history
export HISTFILE=$XDG_DATA_HOME/bash_history

[ -n "$SSH\_AGENT\_PID" ] || eval "$(ssh-agent -s)" > /dev/null

[ -e $HOME/.profile_local ] && . $HOME/.profile_local
